{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homework-app.serviceAccountName" . }}
  namespace: {{ include "homework-app.namespace" . }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
{{- if and .Values.rbac.metricsReader.enabled .Values.rbac.metricsReader.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homework-app.metricsServiceAccountName" . }}
  namespace: {{ include "homework-app.namespace" . }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
  {{- with .Values.rbac.metricsReader.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.rbac.metricsReader.serviceAccount.automount }}
{{- end }}
