apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework-app.fullname" . }}
  namespace: {{ include "homework-app.namespace" . }}
  labels:
    {{- include "homework-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    {{- include "homework-app.selectorLabels" . | nindent 4 }}
