repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami


templates:
  .default: &default
    wait: true
    timeout: 600
    atomic: true
    cleanupOnFail: true

releases:
  - name: kafka-prod
    <<: *default
    namespace: prod
    createNamespace: true
    chart: bitnami/kafka
    version: 25.3.5
    values:
      - kafka-values-prod.yaml

  - name: kafka-dev
    <<: *default
    namespace: dev
    createNamespace: true
    chart: bitnami/kafka
    values:
      - kafka-values-dev.yaml
