apiVersion: v1
kind: Pod
metadata:
  namespace: nginx-distroless
  name: nginx-distroless
  labels:
    app: nginx-distroless
spec:
  containers:
    - name: nginx-distroless
      image: harbor.mvl.test/docker/kyos0109/nginx-distroless
      ports:
        - name: http
          containerPort: 80
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-distroless
  namespace: nginx-distroless
spec:
  selector:
    app: nginx-distroless
  ports:
    - name: http
      port: 80
      targetPort: http