apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-templating
  namespace: argo
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2026-05OTUS/MikhailV0_repo.git
    targetRevision: main
    path: kubernetes-templating/homework-app
    helm:
      parameters:
        - name: replicaCount
          value: "5"
  destination:
    server: https://kubernetes.default.svc
    namespace: homeworkhelm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
