---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-stub-status
  namespace: nginx-monitoring
  labels:
    app: nginx-stub-status
spec:
  selector:
    matchLabels:
      app: nginx-stub-status
  namespaceSelector:
    matchNames:
      - nginx-monitoring
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
