---

apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-config
  namespace: homework
  labels:
    app: homework
data:
  nginx.conf: |
    server {
        listen 8000;
        root /homework;
        index index.html;

        location /conf/ {
            alias /homework/conf/;
            default_type text/plain;
        }
    }

