FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

COPY pyproject.toml ./
RUN uv sync --no-dev

COPY app ./app

CMD ["uv", "run", "kopf", "run", "app/operator.py", "--verbose", "--all-namespaces"]
